In [79]:
import pandas as pd
import numpy as np
import matplotlib as plt
import ast
from collections import Counter

In [68]:
origin_df = pd.read_csv("../data/origin_kaggle_data.csv", encoding='ISO-8859-1',low_memory=False)
paris_df = origin_df[origin_df['city'] == 'Paris']

In [69]:
origin_df.shape

(279712, 33)

In [70]:
origin_df

,listing_id,name,host_id,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,...,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable
0,281420,"Beautiful Flat in le Village Montmartre, Paris",1466919,2011-12-03,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
1,3705183,39 mÃÂ² Paris (Sacre CÃ âur),10328771,2013-11-29,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
2,4082273,"Lovely apartment with Terrace, 60m2",19252768,2014-07-31,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
3,4797344,Cosy studio (close to Eiffel tower),10668311,2013-12-17,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
4,4823489,Close to Eiffel Tower - Beautiful flat : 2 rooms,24837558,2014-12-14,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279707,38338635,Appartement T2 neuf prÃÂ¨s du tram T3a Porte ...,31161181,2015-04-13,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,1,7,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
279708,38538692,Cozy Studio in Montmartre,10294858,2013-11-27,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,7,15,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
279709,38683356,Nice and cosy mini-appartement in Paris,2238502,2012-04-27,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,6,30,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
279710,39659000,Charming apartment near Rue Saint Maur / Oberk...,38633695,2015-07-16,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,3,18,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
279711,40219504,Cosy apartment with view on Canal St Martin,6955618,2013-06-17,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,4,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f

In [71]:
data1 = origin_df.loc[:,["bedrooms",'neighbourhood','district', 'city']]
data1.head()

   bedrooms      neighbourhood district   city
0       1.0  Buttes-Montmartre      NaN  Paris
1       1.0  Buttes-Montmartre      NaN  Paris
2       1.0             Elysee      NaN  Paris
3       1.0          Vaugirard      NaN  Paris
4       1.0              Passy      NaN  Paris

In [72]:
data1["city"].unique()

array(['Paris', 'New York', 'Bangkok', 'Rio de Janeiro', 'Sydney',
       'Istanbul', 'Rome', 'Hong Kong', 'Mexico City', 'Cape Town'],
      dtype=object)

In [73]:
origin_df["price"]

0          53
1         120
2          89
3          58
4          60
         ...
279707    120
279708     60
279709     50
279710    105
279711     70
Name: price, Length: 279712, dtype: int64

In [74]:
origin_df.columns

Index(['listing_id', 'name', 'host_id', 'host_since', 'host_location',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_total_listings_count',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'district', 'city', 'latitude', 'longitude', 'property_type',
       'room_type', 'accommodates', 'bedrooms', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'instant_bookable'],
      dtype='object')

In [75]:
paris_df["amenities"].unique()

array(['["Heating", "Kitchen", "Washer", "Wifi", "Long term stays allowed"]',
       '["Shampoo", "Heating", "Kitchen", "Essentials", "Washer", "Dryer", "Wifi", "Long term stays allowed"]',
       '["Heating", "TV", "Kitchen", "Washer", "Wifi", "Long term stays allowed"]',
       ...,
       '["Paid parking off premises", "Shampoo", "First aid kit", "Heating", "Iron", "Kitchen", "Hair dryer", "Essentials", "Washer", "Breakfast", "Hot water", "Wifi", "Long term stays allowed", "Dedicated workspace", "Host greets you"]',
       '["TV", "Iron", "Kitchen", "Hangers", "Smoke alarm", "Cable TV", "Dedicated workspace", "Hot water", "Heating", "Shampoo", "Elevator", "Essentials", "Washer", "Carbon monoxide alarm", "Wifi"]',
       '["Shower gel", "Shampoo", "Iron", "Heating", "Washer", "Dedicated workspace", "Extra pillows and blankets", "Wifi", "Dishes and silverware", "Kitchen", "Refrigerator", "Cooking basics", "Hot water", "Essentials", "Bed linens", "Dishwasher", "Coffee maker"]'],
      shape=(54198,), dtype=object)

In [76]:
#verify if bedrooms nan is a specific room_type

print("nan count:", paris_df.shape[0] - paris_df["review_scores_rating"].count())
#print(len(data_paris[data_paris["minimum_nights"] > 30]))

nan count: 16654

In [ ]:
paris_df.shape

(64690, 33)

<h1>removing columns and expanding to binary columns</h1>

In [78]:

cols_tokeep = [
    "listing_id", "name", "host_since", "host_is_superhost", "latitude", "longitude",
    "host_total_listings_count", "host_has_profile_pic", "host_identity_verified",
    "room_type", "accommodates", "bedrooms", "amenities", "price",
    "minimum_nights", "maximum_nights", "review_scores_rating",
    "review_scores_cleanliness", "review_scores_checkin",
    "review_scores_communication", "review_scores_location",
    "review_scores_value", "instant_bookable"
]

df1 = paris_df[cols_tokeep].copy()


# parsing amenities
df1["amenities_list"] = df1["amenities"].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith("[") else [])

# all the unique amenities
all_amenities = sorted(set(a for sublist in df1["amenities_list"] for a in sublist))

print(f"Unique amenities: {len(all_amenities)}")

print(all_amenities[:15])

# total columns
num_base_features = len(cols_tokeep) - 1  # minus "amenities"
num_amenities_features = len(all_amenities)
total_columns = num_base_features + num_amenities_features

print(f"Base columns: {num_base_features}")
print(f"Amenities columns: {num_amenities_features}")
print(f"Total expected columns: {total_columns}")

Unique amenities: 750
[' linens', ' toiletries', '100" HDTV with Netflix', '103" TV with Netflix', '2 Plaques électriques electric stove', '2 fours: Micro-onde et chaleur tournante stainless steel oven', '2 réfrigérateur encastrés refrigerator', '23" HDTV with premium cable', '23" TV with Netflix', '24" HDTV', '24-hour fitness center', '31" HDTV with Netflix, standard cable', '32" HDTV', '32" HDTV with Amazon Prime Video, Netflix', '32" HDTV with Netflix, Amazon Prime Video, standard cable']
Base columns: 22
Amenities columns: 750
Total expected columns: 772

<h1>there are too many unique amenities so we take the most used</h1>

In [84]:

# Parse amenities
df1["amenities_list"] = df1["amenities"].apply(
    lambda x: [a.strip().lower() for a in ast.literal_eval(x)] 
    if isinstance(x, str) and x.startswith("[") else []
)

# count the freq of each amenity
amenity_counts = Counter(a for sublist in df1["amenities_list"] for a in sublist)
n_listings = len(df1)

# have only amenities used in at least 1% of listings
threshold = 0.01 * n_listings
common_amenities = {a for a, c in amenity_counts.items() if c >= threshold}

print(f"Unique amenities: {len(amenity_counts)}")
print(f"Frequent amenities (>1%): {len(common_amenities)}")

# binary expension
for a in common_amenities:
    clean_col = "Has_" + a.replace(" ", "_").replace("-", "_").replace("/", "_")
    df1[clean_col] = df1["amenities_list"].apply(lambda x: int(a in x))


final_amenities_cols = [c for c in df1.columns if c.startswith("Has_")]
print(f"Final amenity columns: {len(final_amenities_cols)}")

Unique amenities: 703
Frequent amenities (>1%): 69
Final amenity columns: 69

In [85]:
final_amenities_cols

['Has_air_conditioning',
 'Has_pocket_wifi',
 'Has_shampoo',
 'Has_nespresso_machine',
 'Has_stove',
 'Has_first_aid_kit',
 'Has_room_darkening_shades',
 'Has_hair_dryer',
 'Has_lock_on_bedroom_door',
 'Has_microwave',
 'Has_body_soap',
 'Has_dishwasher',
 'Has_baby_bath',
 'Has_host_greets_you',
 'Has_portable_fans',
 'Has_paid_parking_on_premises',
 'Has_cleaning_before_checkout',
 'Has_elevator',
 'Has_paid_parking_off_premises',
 'Has_tv',
 'Has_patio_or_balcony',
 'Has_washer',
 'Has_private_entrance',
 'Has_shower_gel',
 'Has_crib',
 'Has_hot_water',
 'Has_babysitter_recommendations',
 'Has_dishes_and_silverware',
 'Has_bread_maker',
 'Has_lockbox',
 'Has_fire_extinguisher',
 'Has_bathtub',
 'Has_dedicated_workspace',
 'Has_long_term_stays_allowed',
 'Has_luggage_dropoff_allowed',
 'Has_extra_pillows_and_blankets',
 'Has_cooking_basics',
 'Has_indoor_fireplace',
 'Has_refrigerator',
 'Has_essentials',
 'Has_carbon_monoxide_alarm',
 'Has_changing_table',
 'Has_building_staff',
 'Has_cable_tv',
 'Has_game_console',
 'Has_high_chair',
 'Has_hangers',
 'Has_children’s_books_and_toys',
 'Has_dryer',
 'Has_kitchen',
 'Has_bed_linens',
 'Has_garden_or_backyard',
 'Has_breakfast',
 'Has_laundromat_nearby',
 'Has_free_parking_on_premises',
 'Has_baking_sheet',
 'Has_freezer',
 'Has_children’s_dinnerware',
 'Has_pack_’n_play_travel_crib',
 'Has_free_street_parking',
 'Has_iron',
 'Has_single_level_home',
 'Has_ethernet_connection',
 'Has_oven',
 'Has_smart_lock',
 'Has_coffee_maker',
 'Has_smoke_alarm',
 'Has_wifi',
 'Has_heating']

In [86]:
print(f"Base columns: {num_base_features}")
print(f"Amenities columns: {len(final_amenities_cols)}")
print(f"Total expected columns: {num_base_features+len(final_amenities_cols)}")

Base columns: 22
Amenities columns: 69
Total expected columns: 91

<h1></h1>