In [2]:
import pyairbnb
from typing import List, Dict
import pandas as pd
import numpy as np
import matplotlib as plt
import json
import datetime

In [7]:
pd.set_option('display.max_columns',100)          
pd.set_option('display.max_rows',100)

In [128]:
def paris_airbnb_scraper_json():
    # Paris bounding box coordinates
    paris_coords = {
        "ne_lat": 48.902,   # Northeast latitude
        "ne_long": 2.469,   # Northeast longitude  
        "sw_lat": 48.815,   # Southwest latitude
        "sw_long": 2.224    # Southwest longitude
    }
    
    try:
        dynamic_hash = pyairbnb.fetch_stays_search_hash()
        results = pyairbnb.search_all(
            check_in="2025-12-01",
            check_out="2025-12-31",
            ne_lat=paris_coords["ne_lat"],
            ne_long=paris_coords["ne_long"],
            sw_lat=paris_coords["sw_lat"],
            sw_long=paris_coords["sw_long"],
            zoom_value=2,
            price_min=0,
            price_max=10000,  # Adjust this if you want higher/lower price range
            currency="EUR",
            language="fr",
            hash=dynamic_hash
        )        
        
        print(f"Found {len(results)} listings.")

        with open(f"/results/search_results{datetime.datetime.now().time()}.json", 'w', encoding='utf-8') as f:
            json.dump(results, f, ensure_ascii=False, indent=2)

        
    except Exception as e:
        
        return []

In [69]:
def paris_airbnb_scraper_url():
    url = "https://www.airbnb.fr/s/Paris/homes?refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=weekend_trip&date_picker_type=calendar&search_type=autocomplete_click&monthly_start_date=2025-11-01&monthly_length=3&monthly_end_date=2026-02-01&search_mode=regular_search&price_filter_input_type=2&price_filter_num_nights=1&channel=EXPLORE&zoom_level=11&checkin=2025-10-25&checkout=2025-10-26&acp_id=db9f8d81-98a0-4f97-8e5f-51f6987effdb&source=structured_search_input_header&location_bb=QkObzUAeEgpCQ0MjQA5Zkw%3D%3D"

    # Fetches the live StaysSearch hash first so
    # the persisted query id matches airbnb website.
    dynamic_hash = pyairbnb.fetch_stays_search_hash()
    # Use the URL wrapper
    results = pyairbnb.search_all_from_url(
        url,
        currency="EUR",
        language="fr",
        proxy_url="",
        hash=dynamic_hash, # optional, fallbacks to predefined hash
    )

    # Save results and print count
    with open('search_from_url.json', 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

    print(f"Found {len(results)} listings from URL search.")

In [ ]:
paris_airbnb_scraper_json()

Found 280 listings.

<h3>we have a json file with the listings so now we create a df</h3>

In [6]:
with open("results/search_results.json", "r", encoding="utf-8") as f:
    listings = json.load(f)

# Normalize nested JSON to flat table
df = pd.json_normalize(listings)

In [7]:
df["title"].unique()

array(['Appartement ⋅ Issy-les-Moulineaux', 'Appartement ⋅ Paris',
       "Chambre d'hôtel ⋅ Issy-les-Moulineaux", 'Appartement ⋅ Montreuil',
       'Appartement ⋅ Ivry-sur-Seine', 'Appartement en résidence ⋅ Paris',
       'Appartement ⋅ Courbevoie', 'Appartement ⋅ Neuilly-sur-Seine',
       'Appartement ⋅ Boulogne-Billancourt',
       'Hébergement ⋅ Issy-les-Moulineaux',
       'Appartement ⋅ Levallois-Perret',
       'Appartement en résidence ⋅ Courbevoie', "Appart'hôtel ⋅ Puteaux",
       'Appartement ⋅ Clichy', 'Appartement ⋅ Vanves',
       'Appartement ⋅ Charenton-le-Pont', 'Chambre · Paris',
       'Appartement ⋅ Montrouge',
       'Appartement en résidence ⋅ Saint-Maurice',
       'Chambre · Noisy-le-Sec', 'Appartement ⋅ Suresnes',
       'Appartement en résidence ⋅ Levallois-Perret',
       'Hébergement · Paris', 'Chambre · Les Lilas',
       'Appartement ⋅ Saint-Mandé', 'Chambre · Gentilly',
       'Appartement ⋅ Vincennes', 'Chambre · Suresnes',
       'Appartement ⋅ Les Lilas', 'Chambre · Courbevoie',
       'Hébergement · Boulogne-Billancourt', 'Chambre · Bagnolet',
       'Chambre · Boulogne-Billancourt',
       'Appartement ⋅ Fontenay-sous-Bois', "Maison d'hôtes ⋅ Montreuil",
       'Hébergement ⋅ Bagnolet', 'Appartement ⋅ Puteaux',
       'Chambre · Levallois-Perret', 'Chambres · Paris',
       'Hébergement ⋅ Paris', 'Chambre · Pantin', 'Chambre · Saint-Mandé',
       'Appartement ⋅ Meudon', 'Chambre · Puteaux',
       'Appartement ⋅ Bagnolet'], dtype=object)

In [8]:
df.columns

Index(['room_id', 'category', 'paymentMessages', 'kind', 'name', 'title',
       'type', 'images', 'badges', 'structuredContent.__typename',
       'structuredContent.distance', 'structuredContent.mapCategoryInfo',
       'structuredContent.mapPrimaryLine',
       'structuredContent.mapSecondaryLine', 'structuredContent.primaryLine',
       'structuredContent.secondaryLine', 'structuredContent.reviewSnippet',
       'structuredContent.explanation', 'price.unit.qualifier',
       'price.unit.curency_symbol', 'price.unit.amount',
       'price.total.currency_symbol', 'price.total.amount', 'price.break_down',
       'rating.value', 'rating.reviewCount', 'coordinates.latitude',
       'coordinates.longitud', 'price.unit.discount',
       'passportData.__typename', 'passportData.userId',
       'passportData.contextualUserId', 'passportData.profilePictureUrl',
       'passportData.profileLoggingId', 'passportData.profileA11yLabel',
       'passportData.isVerified', 'passportData.isSuperhost',
       'passportData.name', 'passportData.titleText',
       'passportData.thumbnailUrl', 'passportData.stats',
       'passportData.timeAsHost.__typename', 'passportData.timeAsHost.years',
       'passportData.timeAsHost.months', 'passportData.ratingCount',
       'passportData.ratingAverage', 'passportData.timeAsHost'],
      dtype='object')

In [111]:
#print(df["price.unit.amount"].unique())
#df["price.break_down"][0]
#print(df.head()[5:10])

In [91]:
for c in df.columns:
    print(c)
    #print(df[c].unique())
    print("nan count:", df.shape[0] - df[c].count())

room_id
nan count: 0
category
nan count: 0
paymentMessages
nan count: 0
kind
nan count: 0
name
nan count: 0
title
nan count: 0
type
nan count: 0
images
nan count: 0
badges
nan count: 0
structuredContent.__typename
nan count: 0
structuredContent.distance
nan count: 0
structuredContent.mapCategoryInfo
nan count: 280
structuredContent.mapPrimaryLine
nan count: 0
structuredContent.mapSecondaryLine
nan count: 0
structuredContent.primaryLine
nan count: 0
structuredContent.secondaryLine
nan count: 0
structuredContent.reviewSnippet
nan count: 280
structuredContent.explanation
nan count: 0
price.unit.qualifier
nan count: 0
price.unit.curency_symbol
nan count: 0
price.unit.amount
nan count: 0
price.total.currency_symbol
nan count: 0
price.total.amount
nan count: 0
price.break_down
nan count: 0
rating.value
nan count: 0
rating.reviewCount
nan count: 0
coordinates.latitude
nan count: 0
coordinates.longitud
nan count: 0
price.unit.discount
nan count: 83
passportData.__typename
nan count: 255
passportData.userId
nan count: 255
passportData.contextualUserId
nan count: 255
passportData.profilePictureUrl
nan count: 255
passportData.profileLoggingId
nan count: 280
passportData.profileA11yLabel
nan count: 280
passportData.isVerified
nan count: 255
passportData.isSuperhost
nan count: 255
passportData.name
nan count: 255
passportData.titleText
nan count: 255
passportData.thumbnailUrl
nan count: 255
passportData.stats
nan count: 255
passportData.timeAsHost.__typename
nan count: 256
passportData.timeAsHost.years
nan count: 256
passportData.timeAsHost.months
nan count: 256
passportData.ratingCount
nan count: 255
passportData.ratingAverage
nan count: 255
passportData.timeAsHost
nan count: 280

In [32]:
df.head(3)

,room_id,category,paymentMessages,kind,name,title,type,images,badges,structuredContent.__typename,...,passportData.titleText,passportData.thumbnailUrl,passportData.stats,passportData.timeAsHost.__typename,passportData.timeAsHost.years,passportData.timeAsHost.months,passportData.ratingCount,passportData.ratingAverage,price.unit.discount,passportData.timeAsHost
0,22166982,,"[{'__typename': 'PaymentMessage', 'text': 'Ann...",,Chambre double au paradis !,Hébergement · Puerto Villamil,,[{'url': 'https://a0.muscache.com/im/pictures/...,[],ExploreStructuredContent,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,979204724829796133,,"[{'__typename': 'PaymentMessage', 'text': 'Ann...",,"Appartement privé à Galapagos, Santa Cruz",Chambre · Puerto Ayora,,[{'url': 'https://a0.muscache.com/im/pictures/...,[GUEST_FAVORITE],ExploreStructuredContent,...,Superhôte,https://a0.muscache.com/im/pictures/user/User/...,"[{'__typename': 'HostStat', 'a11yValue': '49 c...",TimeAsUser,3.0,4.0,49.0,4.96,NaN,NaN
2,1408025049562196389,,[],,Séjour confortable sur une île avec balcon et ...,Appartement ⋅ Puerto Ayora,,[{'url': 'https://a0.muscache.com/im/pictures/...,[GUEST_FAVORITE],ExploreStructuredContent,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.0,NaN

<h3>renaming the columns to start merging and cleaning</h3>

In [33]:
cols = {
    "room_id": "id",
    "name": "name",
    "title": "title",
    "price.unit.amount": "price_night",
    "rating.value": "rating",
    "rating.reviewCount": "reviews",
    "coordinates.latitude": "lat",
    "coordinates.longitud": "lon"
}

df = df[list(cols.keys())].rename(columns=cols)

In [34]:
df.head()

,id,name,title,price_night,rating,reviews,lat,lon
0,22166982,Chambre double au paradis !,Hébergement · Puerto Villamil,16.0,4.56,160,-0.95300,-90.9673
1,979204724829796133,"Appartement privé à Galapagos, Santa Cruz",Chambre · Puerto Ayora,21.0,4.96,49,-0.73710,-90.3141
2,1408025049562196389,Séjour confortable sur une île avec balcon et ...,Appartement ⋅ Puerto Ayora,65.0,4.94,36,-0.73920,-90.3107
3,1272651730508265418,Villa Náutica,Hébergement ⋅ Puerto Ayora,201.0,5.00,25,-0.73610,-90.3111
4,1098134088737119696,Chambre dans la maison de Lara,Chambre · Puerto Ayora,20.0,4.82,39,-0.74249,-90.3156

<h2>convert types</h2>

In [35]:
df["price_night"] = pd.to_numeric(df["price_night"], errors="coerce")
df["rating"] = pd.to_numeric(df["rating"], errors="coerce")
df["reviews"] = pd.to_numeric(df["reviews"], errors="coerce")

In [36]:
df.head()

,id,name,title,price_night,rating,reviews,lat,lon
0,22166982,Chambre double au paradis !,Hébergement · Puerto Villamil,16.0,4.56,160,-0.95300,-90.9673
1,979204724829796133,"Appartement privé à Galapagos, Santa Cruz",Chambre · Puerto Ayora,21.0,4.96,49,-0.73710,-90.3141
2,1408025049562196389,Séjour confortable sur une île avec balcon et ...,Appartement ⋅ Puerto Ayora,65.0,4.94,36,-0.73920,-90.3107
3,1272651730508265418,Villa Náutica,Hébergement ⋅ Puerto Ayora,201.0,5.00,25,-0.73610,-90.3111
4,1098134088737119696,Chambre dans la maison de Lara,Chambre · Puerto Ayora,20.0,4.82,39,-0.74249,-90.3156

In [42]:
np.sort(df["price_night"].unique())

array([  1.,  11.,  12.,  14.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  43.,  44.,  45.,
        46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  55.,  56.,  57.,
        58.,  59.,  60.,  61.,  62.,  63.,  65.,  66.,  70.,  72.,  73.,
        74.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  87.,
        90.,  91.,  92.,  95.,  97.,  99., 102., 103., 111., 117., 122.,
       125., 127., 129., 132., 133., 135., 138., 148., 155., 158., 163.,
       189., 201., 208., 224., 301., 369., 500., 610.])

<h2>drop rows that have null values in important columns</h2>

In [37]:
df = df.dropna(subset=["price_night", "lat", "lon"])

In [38]:
df.to_csv("paris_airbnb_dataset.csv", index=False)

In [10]:
df["structuredContent.__typename"]

0      ExploreStructuredContent
1      ExploreStructuredContent
2      ExploreStructuredContent
3      ExploreStructuredContent
4      ExploreStructuredContent
                 ...
275    ExploreStructuredContent
276    ExploreStructuredContent
277    ExploreStructuredContent
278    ExploreStructuredContent
279    ExploreStructuredContent
Name: structuredContent.__typename, Length: 280, dtype: object


Scraper:
we drop the category, payement message, kind,  column